[versions]
axion = "1.18.18"
jackson = "2.19.0"
jreleaser = "1.18.0"
junit = "5.12.2"
logback = "1.5.18"
lombok = "8.13.1"
mockito = "5.17.0"
okhttp = "5.0.0-alpha.14"
reactor = "2024.0.5"
slf4J = "2.0.17"

[libraries]
jackson = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-datatype-java8 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
jackson-module-parameter-names = { module = "com.fasterxml.jackson.module:jackson-module-parameter-names", version.ref = "jackson" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
reactor-bom = { module = "io.projectreactor:reactor-bom", version.ref = "reactor" }
reactor-core = { module = "io.projectreactor:reactor-core" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4J" }

[bundles]
jackson = ["jackson", "jackson-datatype-java8", "jackson-datatype-jsr310", "jackson-module-parameter-names"]
junit = ["junit-jupiter", "junit-jupiter-params"]
mockito = ["mockito-core", "mockito-junit-jupiter"]

[plugins]
axion = { id = "pl.allegro.tech.build.axion-release", version.ref = "axion" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
