name: Update files
on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Update files
        uses: MathieuSoysal/file-updater-for-release@v1
        with:
          files: README.md
          prefix: "tech.ixirsii:clash4j:"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "docs(readme): Update README"
          title: Update README
          body: Update README to reflect release changes
          branch: docs/readme
